name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.13' 
      - run: go test ./... -v -count=1 -shuffle=on
      - run: gofmt -s -w . && git diff --exit-code
      - run: go mod tidy && git diff --exit-code
      - uses: golangci/golangci-lint-action@v3
